[package]
edition.workspace = true
name = "bladeworks-runtime"
version.workspace = true

[dependencies]
katana-executor.workspace = true
katana-primitives.workspace = true
katana-provider.workspace = true
