[package]
name = "bladeworks-db"
version.workspace = true
edition.workspace = true

[dependencies]
katana-db = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.0-alpha.0", version = "1.0.0-alpha.0" }
