[package]
edition.workspace = true
name = "bladeworks-db"
version.workspace = true

[dependencies]
anyhow = "1.0.86"
bladeworks-context.workspace = true
katana-db.workspace = true
katana-primitives.workspace = true
katana-provider.workspace = true
parking_lot = "0.12.3"
