[package]
edition.workspace = true
name = "bladeworks-db"
version.workspace = true

[dependencies]
bladeworks-context.workspace = true
katana-db.workspace = true
katana-primitives.workspace = true
katana-provider.workspace = true
